[package]
name = "expo-kit-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
handlebars = "4.3.2"
serde = { version = "1.0", features = ["derive"] }
fs_extra = "1.2"
clap = "4.5.19"
inquire = "0.7.5"
serde_json = "1.0.128"
console = "0.15.8"
once_cell = "1.20.2"
